## 1. The mathematical formulas for each of the 33 moments

`N=32768`, `Rs=1/T0`, `x_t=x[t]`, `conj(x_t)=\bar{x}_t`。

```text
M21[-1] = (1/N) sum_t |x_t|^2        * exp(-j2pi*(-Rs)*t)
M21[ 0] = (1/N) sum_t |x_t|^2        * exp(-j2pi*( 0  )*t)
M21[ 1] = (1/N) sum_t |x_t|^2        * exp(-j2pi*( Rs )*t)

M40[-2] = (1/N) sum_t x_t^4         * exp(-j2pi*(4f0 - 2Rs)*t)
M40[-1] = (1/N) sum_t x_t^4         * exp(-j2pi*(4f0 -  Rs)*t)
M40[ 0] = (1/N) sum_t x_t^4         * exp(-j2pi*(4f0       )*t)
M40[ 1] = (1/N) sum_t x_t^4         * exp(-j2pi*(4f0 +  Rs)*t)
M40[ 2] = (1/N) sum_t x_t^4         * exp(-j2pi*(4f0 + 2Rs)*t)

M42[-2] = (1/N) sum_t |x_t|^4       * exp(-j2pi*(-2Rs)*t)
M42[-1] = (1/N) sum_t |x_t|^4       * exp(-j2pi*(- Rs)*t)
M42[ 0] = (1/N) sum_t |x_t|^4       * exp(-j2pi*( 0  )*t)
M42[ 1] = (1/N) sum_t |x_t|^4       * exp(-j2pi*( Rs )*t)
M42[ 2] = (1/N) sum_t |x_t|^4       * exp(-j2pi*(2Rs )*t)

M44[-2] = (1/N) sum_t \bar{x}_t^4   * exp(-j2pi*(-4f0 - 2Rs)*t)
M44[-1] = (1/N) sum_t \bar{x}_t^4   * exp(-j2pi*(-4f0 -  Rs)*t)
M44[ 0] = (1/N) sum_t \bar{x}_t^4   * exp(-j2pi*(-4f0       )*t)
M44[ 1] = (1/N) sum_t \bar{x}_t^4   * exp(-j2pi*(-4f0 +  Rs)*t)
M44[ 2] = (1/N) sum_t \bar{x}_t^4   * exp(-j2pi*(-4f0 + 2Rs)*t)

M61[-2] = (1/N) sum_t x_t^5\bar{x}_t * exp(-j2pi*(4f0 - 2Rs)*t)
M61[-1] = (1/N) sum_t x_t^5\bar{x}_t * exp(-j2pi*(4f0 -  Rs)*t)
M61[ 0] = (1/N) sum_t x_t^5\bar{x}_t * exp(-j2pi*(4f0       )*t)
M61[ 1] = (1/N) sum_t x_t^5\bar{x}_t * exp(-j2pi*(4f0 +  Rs)*t)
M61[ 2] = (1/N) sum_t x_t^5\bar{x}_t * exp(-j2pi*(4f0 + 2Rs)*t)

M63[-2] = (1/N) sum_t |x_t|^6       * exp(-j2pi*(-2Rs)*t)
M63[-1] = (1/N) sum_t |x_t|^6       * exp(-j2pi*(- Rs)*t)
M63[ 0] = (1/N) sum_t |x_t|^6       * exp(-j2pi*( 0  )*t)
M63[ 1] = (1/N) sum_t |x_t|^6       * exp(-j2pi*( Rs )*t)
M63[ 2] = (1/N) sum_t |x_t|^6       * exp(-j2pi*(2Rs )*t)

M65[-2] = (1/N) sum_t x_t\bar{x}_t^5 * exp(-j2pi*(-4f0 - 2Rs)*t)
M65[-1] = (1/N) sum_t x_t\bar{x}_t^5 * exp(-j2pi*(-4f0 -  Rs)*t)
M65[ 0] = (1/N) sum_t x_t\bar{x}_t^5 * exp(-j2pi*(-4f0       )*t)
M65[ 1] = (1/N) sum_t x_t\bar{x}_t^5 * exp(-j2pi*(-4f0 +  Rs)*t)
M65[ 2] = (1/N) sum_t x_t\bar{x}_t^5 * exp(-j2pi*(-4f0 + 2Rs)*t)
```

## 2. Possible correspondences among the 33 Moments

```text
M21[-1] = conj(M21[ 1])
M21[ 0] is real

M42[-2] = conj(M42[ 2])
M42[-1] = conj(M42[ 1])
M42[ 0] is real

M63[-2] = conj(M63[ 2])
M63[-1] = conj(M63[ 1])
M63[ 0] is real

M44[-2] = conj(M40[ 2])
M44[-1] = conj(M40[ 1])
M44[ 0] = conj(M40[ 0])
M44[ 1] = conj(M40[-1])
M44[ 2] = conj(M40[-2])

M65[-2] = conj(M61[ 2])
M65[-1] = conj(M61[ 1])
M65[ 0] = conj(M61[ 0])
M65[ 1] = conj(M61[-1])
M65[ 2] = conj(M61[-2])
```

## 3. The mathematical formula composed of each of the 33 cumulants

```text
C21[-1] = M21[-1]
C21[ 0] = M21[ 0]
C21[ 1] = M21[ 1]

C40[-2] = M40[-2]
C40[-1] = M40[-1]
C40[ 0] = M40[ 0]
C40[ 1] = M40[ 1]
C40[ 2] = M40[ 2]

C42[-2] = M42[-2] - 2*M21[-1]^2
C42[-1] = M42[-1] - 4*M21[-1]*M21[0]
C42[ 0] = M42[ 0] - 2*M21[0]^2 - 4*M21[-1]*M21[1]
C42[ 1] = M42[ 1] - 4*M21[0]*M21[1]
C42[ 2] = M42[ 2] - 2*M21[1]^2

C44[-2] = M44[-2]
C44[-1] = M44[-1]
C44[ 0] = M44[ 0]
C44[ 1] = M44[ 1]
C44[ 2] = M44[ 2]

C61[-2] = M61[-2] - 5*(M40[-1]*M21[-1] + M40[-2]*M21[0])
C61[-1] = M61[-1] - 5*(M40[ 0]*M21[-1] + M40[-1]*M21[0] + M40[-2]*M21[1])
C61[ 0] = M61[ 0] - 5*(M40[ 1]*M21[-1] + M40[ 0]*M21[0] + M40[-1]*M21[1])
C61[ 1] = M61[ 1] - 5*(M40[ 2]*M21[-1] + M40[ 1]*M21[0] + M40[ 0]*M21[1])
C61[ 2] = M61[ 2] - 5*(M40[ 2]*M21[0] + M40[ 1]*M21[1])

C63[-2] = M63[-2] - 9*(M42[-1]*M21[-1] + M42[-2]*M21[0]) + 36*M21[-1]^2*M21[0]
C63[-1] = M63[-1] - 9*(M42[ 0]*M21[-1] + M42[-1]*M21[0] + M42[-2]*M21[1]) + 36*(M21[-1]^2*M21[1] + M21[-1]*M21[0]^2)
C63[ 0] = M63[ 0] - 9*(M42[ 1]*M21[-1] + M42[ 0]*M21[0] + M42[-1]*M21[1]) + 72*M21[-1]*M21[0]*M21[1] + 12*M21[0]^3
C63[ 1] = M63[ 1] - 9*(M42[ 2]*M21[-1] + M42[ 1]*M21[0] + M42[ 0]*M21[1]) + 36*(M21[-1]*M21[1]^2 + M21[0]^2*M21[1])
C63[ 2] = M63[ 2] - 9*(M42[ 2]*M21[0] + M42[ 1]*M21[1]) + 36*M21[0]*M21[1]^2

C65[-2] = M65[-2] - 5*(M44[-1]*M21[-1] + M44[-2]*M21[0])
C65[-1] = M65[-1] - 5*(M44[ 0]*M21[-1] + M44[-1]*M21[0] + M44[-2]*M21[1])
C65[ 0] = M65[ 0] - 5*(M44[ 1]*M21[-1] + M44[ 0]*M21[0] + M44[-1]*M21[1])
C65[ 1] = M65[ 1] - 5*(M44[ 2]*M21[-1] + M44[ 1]*M21[0] + M44[ 0]*M21[1])
C65[ 2] = M65[ 2] - 5*(M44[ 2]*M21[0] + M44[ 1]*M21[1])
```

## 4. 33 possible correspondences of cumulants

```text
C21[-1] = conj(C21[ 1])
C21[ 0] is real

C42[-2] = conj(C42[ 2])
C42[-1] = conj(C42[ 1])
C42[ 0] is real

C63[-2] = conj(C63[ 2])
C63[-1] = conj(C63[ 1])
C63[ 0] is real

C44[-2] = conj(C40[ 2])
C44[-1] = conj(C40[ 1])
C44[ 0] = conj(C40[ 0])
C44[ 1] = conj(C40[-1])
C44[ 2] = conj(C40[-2])

C65[-2] = conj(C61[ 2])
C65[-1] = conj(C61[ 1])
C65[ 0] = conj(C61[ 0])
C65[ 1] = conj(C61[-1])
C65[ 2] = conj(C61[-2])
```

## 5. Verification

In [1]:
from pathlib import Path
import sys

import numpy as np
import pandas as pd

BOI_DIR = Path('/home/ruilin/SPL_Surreal/SPL_code/boi_shift_fft3_cfpattern_spl')
DATASET_ROOT = Path('/home/ruilin/SPL_Surreal/CSPB.ML_dataset')

if str(BOI_DIR) not in sys.path:
    sys.path.insert(0, str(BOI_DIR))

from helper_function import pre_cc_matrix_core_from_old as cc

SAMPLES_PER_SIG = 32768
K = 5
T0 = 8.0
f0 = 0.0

FIRST15_NM = list(cc.CC_NM[:15])
FIRST15_LABELS = cc.CC_COL_LABELS[:15]
K_LIST = list(cc.CC_K_LIST)
K_TO_ROW = {k: i for i, k in enumerate(K_LIST)}
NM_TO_COL = {nm: i for i, nm in enumerate(FIRST15_NM)}

ACTIVE_NM = [
    (2, 1),
    (4, 0), (4, 2), (4, 4),
    (6, 1), (6, 3), (6, 5),
]


def load_tim_iq(path, samples_per_sig=SAMPLES_PER_SIG):
    raw = np.fromfile(path, dtype=np.float32)
    need = 2 + 2 * int(samples_per_sig)
    if raw.size < need:
        raise ValueError(f'{path}: {raw.size} floats < required {need}')
    iq = raw[2:need]
    return iq[0::2].astype(np.float64) + 1j * iq[1::2].astype(np.float64)


def find_one_tim():
    preferred = DATASET_ROOT / 'CSPB_ML_2018_Data' / 'Batch_Dir_25' / 'signal_96002.tim'
    if preferred.exists():
        return preferred
    candidates = [
        DATASET_ROOT / 'CSPB_ML_2018_Data' / 'Batch_Dir_1',
        DATASET_ROOT / 'CSPB_ML_2018_Data' / 'Batch_Dir_25',
        DATASET_ROOT / 'CSPB_ML_2022_Data' / 'Batch_Dir_1',
    ]
    for directory in candidates:
        if directory.exists():
            found = sorted(directory.glob('signal_*.tim'))
            if found:
                return found[0]
    raise FileNotFoundError('No .tim file found in the expected CSPB.ML_dataset locations.')


def seq_at(seq, k):
    return seq[K_TO_ROW[int(k)]] if int(k) in K_TO_ROW else 0.0 + 0.0j


def conv2_at(a, b, k):
    out = 0.0 + 0.0j
    for ka in K_LIST:
        kb = int(k) - ka
        if kb in K_TO_ROW:
            out += seq_at(a, ka) * seq_at(b, kb)
    return out


def conv3_at(a, b, c, k):
    out = 0.0 + 0.0j
    for ka in K_LIST:
        for kb in K_LIST:
            kc = int(k) - ka - kb
            if kc in K_TO_ROW:
                out += seq_at(a, ka) * seq_at(b, kb) * seq_at(c, kc)
    return out


def mask_sequence(seq, nm):
    out = np.zeros_like(seq, dtype=np.complex128)
    for k in cc.get_allowed_k_list(cc.qpsk, *nm):
        if k in K_TO_ROW:
            out[K_TO_ROW[k]] = seq[K_TO_ROW[k]]
    return out


def rel_err(a, b):
    return abs(a - b) / max(1.0, abs(a), abs(b))


def check_equal(name, lhs, rhs, rows):
    rows.append({
        'check': name,
        'abs_err': abs(lhs - rhs),
        'rel_err': rel_err(lhs, rhs),
        'lhs': lhs,
        'rhs': rhs,
    })


def complex_table(matrix, digits=4):
    def fmt(z):
        z = complex(z)
        if abs(z) < 10 ** (-(digits + 2)):
            return '0'
        return f'{z.real:.{digits}e}{z.imag:+.{digits}e}j'
    return pd.DataFrame(
        [[fmt(z) for z in row] for row in matrix],
        index=pd.Index(K_LIST, name='k'),
        columns=FIRST15_LABELS,
    )


def active_values(matrix):
    values = []
    for nm in ACTIVE_NM:
        col = NM_TO_COL[nm]
        for k in cc.get_allowed_k_list(cc.qpsk, *nm):
            values.append(matrix[K_TO_ROW[k], col])
    return np.asarray(values, dtype=np.complex128)


tim_path = find_one_tim()
x = load_tim_iq(tim_path)
print(f'Loaded: {tim_path}')
print(f'x shape: {x.shape}, dtype: {x.dtype}, T0={T0}, f0={f0}')

# 1) Compute masked cyclic moments with the source function.
moment_sequences = {}
for nm in ACTIVE_NM:
    moment_sequences[nm] = cc.cyclic_moment_sequence_tau0_pattern(
        x,
        T0,
        f0,
        nm[0],
        nm[1],
        K,
        cc.get_allowed_k_list(cc.qpsk, *nm),
        remove_mean=False,
    )

moment_matrix_11x15 = np.zeros((len(K_LIST), len(FIRST15_NM)), dtype=np.complex128)
for nm, seq in moment_sequences.items():
    moment_matrix_11x15[:, NM_TO_COL[nm]] = mask_sequence(seq, nm)

# 2) Compute source cumulants with the original source flow.
source_cc = cc.build_estimated_cc_matrix_11x24_from_signal_pattern(
    x,
    T0,
    f0,
    cc.qpsk,
    remove_mean=False,
    max_k=K,
)['matrix_complex'][:, :15]

# 3) Compute cumulants again from the fixed 33-moment formulas.
M21 = moment_sequences[(2, 1)]
M40 = moment_sequences[(4, 0)]
M42 = moment_sequences[(4, 2)]
M44 = moment_sequences[(4, 4)]
M61 = moment_sequences[(6, 1)]
M63 = moment_sequences[(6, 3)]
M65 = moment_sequences[(6, 5)]

formula_sequences = {
    (2, 1): M21.copy(),
    (4, 0): M40.copy(),
    (4, 4): M44.copy(),
}

c42 = np.zeros(len(K_LIST), dtype=np.complex128)
c61 = np.zeros(len(K_LIST), dtype=np.complex128)
c63 = np.zeros(len(K_LIST), dtype=np.complex128)
c65 = np.zeros(len(K_LIST), dtype=np.complex128)
for k in K_LIST:
    row = K_TO_ROW[k]
    c42[row] = seq_at(M42, k) - 2.0 * conv2_at(M21, M21, k)
    c61[row] = seq_at(M61, k) - 5.0 * conv2_at(M40, M21, k)
    c63[row] = (
        seq_at(M63, k)
        - 9.0 * conv2_at(M42, M21, k)
        + 12.0 * conv3_at(M21, M21, M21, k)
    )
    c65[row] = seq_at(M65, k) - 5.0 * conv2_at(M44, M21, k)

formula_sequences[(4, 2)] = mask_sequence(c42, (4, 2))
formula_sequences[(6, 1)] = mask_sequence(c61, (6, 1))
formula_sequences[(6, 3)] = mask_sequence(c63, (6, 3))
formula_sequences[(6, 5)] = mask_sequence(c65, (6, 5))

formula_cc_11x15 = np.zeros_like(source_cc)
for nm, seq in formula_sequences.items():
    formula_cc_11x15[:, NM_TO_COL[nm]] = mask_sequence(seq, nm)

# 4) Verify moment symmetry.
moment_checks = []
check_equal('M21[-1] = conj(M21[1])', seq_at(M21, -1), np.conj(seq_at(M21, 1)), moment_checks)
check_equal('imag(M21[0]) = 0', seq_at(M21, 0).imag, 0.0, moment_checks)
check_equal('M42[-2] = conj(M42[2])', seq_at(M42, -2), np.conj(seq_at(M42, 2)), moment_checks)
check_equal('M42[-1] = conj(M42[1])', seq_at(M42, -1), np.conj(seq_at(M42, 1)), moment_checks)
check_equal('imag(M42[0]) = 0', seq_at(M42, 0).imag, 0.0, moment_checks)
check_equal('M63[-2] = conj(M63[2])', seq_at(M63, -2), np.conj(seq_at(M63, 2)), moment_checks)
check_equal('M63[-1] = conj(M63[1])', seq_at(M63, -1), np.conj(seq_at(M63, 1)), moment_checks)
check_equal('imag(M63[0]) = 0', seq_at(M63, 0).imag, 0.0, moment_checks)
for k in [-2, -1, 0, 1, 2]:
    check_equal(f'M44[{k}] = conj(M40[{-k}])', seq_at(M44, k), np.conj(seq_at(M40, -k)), moment_checks)
    check_equal(f'M65[{k}] = conj(M61[{-k}])', seq_at(M65, k), np.conj(seq_at(M61, -k)), moment_checks)

moment_check_df = pd.DataFrame(moment_checks)

# 5) Verify formula-derived cumulants against the source cumulants.
formula_abs_err = np.max(np.abs(active_values(formula_cc_11x15) - active_values(source_cc)))
formula_rel_err = np.max([
    rel_err(a, b)
    for a, b in zip(active_values(formula_cc_11x15), active_values(source_cc))
])
formula_check_df = pd.DataFrame([{
    'check': '33 active C(n,m,k) from fixed formulas == source partition/convolution flow',
    'max_abs_err': formula_abs_err,
    'max_rel_err': formula_rel_err,
}])

# 6) Verify cumulant symmetry.
def C(nm, k):
    return source_cc[K_TO_ROW[k], NM_TO_COL[nm]]

cumulant_checks = []
check_equal('C21[-1] = conj(C21[1])', C((2, 1), -1), np.conj(C((2, 1), 1)), cumulant_checks)
check_equal('imag(C21[0]) = 0', C((2, 1), 0).imag, 0.0, cumulant_checks)
check_equal('C42[-2] = conj(C42[2])', C((4, 2), -2), np.conj(C((4, 2), 2)), cumulant_checks)
check_equal('C42[-1] = conj(C42[1])', C((4, 2), -1), np.conj(C((4, 2), 1)), cumulant_checks)
check_equal('imag(C42[0]) = 0', C((4, 2), 0).imag, 0.0, cumulant_checks)
check_equal('C63[-2] = conj(C63[2])', C((6, 3), -2), np.conj(C((6, 3), 2)), cumulant_checks)
check_equal('C63[-1] = conj(C63[1])', C((6, 3), -1), np.conj(C((6, 3), 1)), cumulant_checks)
check_equal('imag(C63[0]) = 0', C((6, 3), 0).imag, 0.0, cumulant_checks)
for k in [-2, -1, 0, 1, 2]:
    check_equal(f'C44[{k}] = conj(C40[{-k}])', C((4, 4), k), np.conj(C((4, 0), -k)), cumulant_checks)
    check_equal(f'C65[{k}] = conj(C61[{-k}])', C((6, 5), k), np.conj(C((6, 1), -k)), cumulant_checks)

cumulant_check_df = pd.DataFrame(cumulant_checks)

print('Moment relation checks:')
display(moment_check_df[['check', 'abs_err', 'rel_err']])
print('Cumulant formula check:')
display(formula_check_df)
print('Cumulant relation checks:')
display(cumulant_check_df[['check', 'abs_err', 'rel_err']])

print('Moment matrix, complex values, 11 x 15:')
display(complex_table(moment_matrix_11x15))
print('Cumulant matrix from source flow, complex values, 11 x 15:')
display(complex_table(source_cc))

Loaded: /home/ruilin/SPL_Surreal/CSPB.ML_dataset/CSPB_ML_2018_Data/Batch_Dir_25/signal_96002.tim
x shape: (32768,), dtype: complex128, T0=8.0, f0=0.0
Moment relation checks:

                     check       abs_err       rel_err
0   M21[-1] = conj(M21[1])  0.000000e+00  0.000000e+00
1         imag(M21[0]) = 0  0.000000e+00  0.000000e+00
2   M42[-2] = conj(M42[2])  6.938894e-18  6.938894e-18
3   M42[-1] = conj(M42[1])  0.000000e+00  0.000000e+00
4         imag(M42[0]) = 0  1.659326e-18  1.659326e-18
5   M63[-2] = conj(M63[2])  2.288783e-16  2.288783e-16
6   M63[-1] = conj(M63[1])  5.551115e-17  4.989392e-17
7         imag(M63[0]) = 0  1.409190e-18  1.409190e-18
8   M44[-2] = conj(M40[2])  0.000000e+00  0.000000e+00
9   M65[-2] = conj(M61[2])  1.570092e-16  1.570092e-16
10  M44[-1] = conj(M40[1])  0.000000e+00  0.000000e+00
11  M65[-1] = conj(M61[1])  2.220446e-16  2.059799e-16
12   M44[0] = conj(M40[0])  0.000000e+00  0.000000e+00
13   M65[0] = conj(M61[0])  2.220446e-16  1.744152e-16
14  M44[1] = conj(M40[-1])  0.000000e+00  0.000000e+00
15  M65[1] = conj(M61[-1])  1.387779e-16  1.387779e-16
16  M44[2] = conj(M40[-2])  0.000000e+00  0.000000e+00
17  M65[2] = conj(M61[-2])  8.326673e-17  8.326673e-17

Cumulant formula check:

,check,max_abs_err,max_rel_err
0,"33 active C(n,m,k) from fixed formulas == sour...",7.105427e-15,2.586793e-15

Cumulant relation checks:

                     check       abs_err       rel_err
0   C21[-1] = conj(C21[1])  0.000000e+00  0.000000e+00
1         imag(C21[0]) = 0  0.000000e+00  0.000000e+00
2   C42[-2] = conj(C42[2])  6.938894e-18  6.938894e-18
3   C42[-1] = conj(C42[1])  0.000000e+00  0.000000e+00
4         imag(C42[0]) = 0  1.659326e-18  1.659326e-18
5   C63[-2] = conj(C63[2])  5.551115e-17  5.551115e-17
6   C63[-1] = conj(C63[1])  5.551115e-17  5.551115e-17
7         imag(C63[0]) = 0  2.822985e-17  2.822985e-17
8   C44[-2] = conj(C40[2])  0.000000e+00  0.000000e+00
9   C65[-2] = conj(C61[2])  1.570092e-16  1.570092e-16
10  C44[-1] = conj(C40[1])  0.000000e+00  0.000000e+00
11  C65[-1] = conj(C61[1])  2.220446e-16  2.220446e-16
12   C44[0] = conj(C40[0])  0.000000e+00  0.000000e+00
13   C65[0] = conj(C61[0])  2.220446e-16  2.220446e-16
14  C44[1] = conj(C40[-1])  0.000000e+00  0.000000e+00
15  C65[1] = conj(C61[-1])  1.387779e-16  1.387779e-16
16  C44[2] = conj(C40[-2])  0.000000e+00  0.000000e+00
17  C65[2] = conj(C61[-2])  8.326673e-17  8.326673e-17

Moment matrix, complex values, 11 x 15:

,"C(2,0)","C(2,1)","C(2,2)","C(4,0)","C(4,1)","C(4,2)","C(4,3)","C(4,4)","C(6,0)","C(6,1)","C(6,2)","C(6,3)","C(6,4)","C(6,5)","C(6,6)"
k,,,,,,,,,,,,,,,
-5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
-4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
-3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
-2,0,0,0,-8.5934e-03+4.7254e-02j,0,-5.7823e-02-2.1476e-02j,0,-1.9757e-02-5.9217e-02j,0,8.5482e-02+6.5716e-01j,0,-5.3085e-01-2.0164e-01j,0,-5.5842e-02-4.2959e-01j,0
-1,0,-1.4668e-02-6.7512e-03j,0,-1.8574e-03-4.2192e-02j,0,-1.1835e-01-3.9324e-02j,0,-1.2737e-01-1.3351e-02j,0,-1.9891e-01-3.5694e-01j,0,-1.0870e+00-2.3712e-01j,0,-1.0726e+00+1.0721e-01j,0
0,0,1.9847e+00+0.0000e+00j,0,1.0956e-02-1.7632e-01j,0,7.1077e+00+1.6593e-18j,0,1.0956e-02+1.7632e-01j,0,-9.7313e-02-1.2694e+00j,0,3.5893e+01+1.4092e-18j,0,-9.7313e-02+1.2694e+00j,0
1,0,-1.4668e-02+6.7512e-03j,0,-1.2737e-01+1.3351e-02j,0,-1.1835e-01+3.9324e-02j,0,-1.8574e-03+4.2192e-02j,0,-1.0726e+00-1.0721e-01j,0,-1.0870e+00+2.3712e-01j,0,-1.9891e-01+3.5694e-01j,0
2,0,0,0,-1.9757e-02+5.9217e-02j,0,-5.7823e-02+2.1476e-02j,0,-8.5934e-03-4.7254e-02j,0,-5.5842e-02+4.2959e-01j,0,-5.3085e-01+2.0164e-01j,0,8.5482e-02-6.5716e-01j,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

Cumulant matrix from source flow, complex values, 11 x 15:

,"C(2,0)","C(2,1)","C(2,2)","C(4,0)","C(4,1)","C(4,2)","C(4,3)","C(4,4)","C(6,0)","C(6,1)","C(6,2)","C(6,3)","C(6,4)","C(6,5)","C(6,6)"
k,,,,,,,,,,,,,,,
-5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
-4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
-3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
-2,0,0,0,-8.5934e-03+4.7254e-02j,0,-5.8163e-02-2.1872e-02j,0,-1.9757e-02-5.9217e-02j,0,1.7204e-01+1.8509e-01j,0,5.0088e-01+1.8373e-01j,0,1.3132e-01+1.5276e-01j,0
-1,0,-1.4668e-02-6.7512e-03j,0,-1.8574e-03-4.2192e-02j,0,-1.9068e-03+1.4272e-02j,0,-1.2737e-01-1.3351e-02j,0,-1.7276e-01+5.2944e-02j,0,-1.2372e-01-5.9561e-02j,0,1.8272e-01+2.4932e-01j,0
0,0,1.9847e+00+0.0000e+00j,0,1.0956e-02-1.7632e-01j,0,-7.7127e-01+1.6593e-18j,0,1.0956e-02+1.7632e-01j,0,-2.1738e-01+4.7402e-01j,0,2.7468e+00-2.8230e-17j,0,-2.1738e-01-4.7402e-01j,0
1,0,-1.4668e-02+6.7512e-03j,0,-1.2737e-01+1.3351e-02j,0,-1.9068e-03-1.4272e-02j,0,-1.8574e-03+4.2192e-02j,0,1.8272e-01-2.4932e-01j,0,-1.2372e-01+5.9561e-02j,0,-1.7276e-01-5.2944e-02j,0
2,0,0,0,-1.9757e-02+5.9217e-02j,0,-5.8163e-02+2.1872e-02j,0,-8.5934e-03-4.7254e-02j,0,1.3132e-01-1.5276e-01j,0,5.0088e-01-1.8373e-01j,0,1.7204e-01-1.8509e-01j,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0